version: "3.8"

services:
  postgresdb:
    image: postgres:16
    restart: always
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=mipass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quarkus_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net_postgres

volumes:
  postgres-data: {}

networks:
  net_postgres:
    driver: bridge